M48
; DRILL file {KiCad (6.0.1)} date Sun Mar 13 01:10:26 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-13T01:10:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X173.876Y-87.394
T2
X130.126Y-136.394
T3
X120.126Y-136.394
X180.476Y-77.114
T0
M30
